---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "devel"
    labels:
      - "dependabot"
      - "gomod"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "devel"
    labels:
      - "dependabot"
      - "github-actions"
