project_name: nginx-conf-generator
env:
  - CGO_ENABLED=0
  - GOFLAGS=-mod=vendor
  - GO111MODULE=auto

before:
  hooks:
    - go mod vendor

builds:
  - id: binary
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
    main: ./cmd/nginx-conf-generator/main.go