---
project_name: nginx-conf-generator
env:
  - CGO_ENABLED=0
  - GOFLAGS=-mod=vendor
  - GO111MODULE=auto
before:
  hooks:
    - go mod vendor
archives:
  - replacements:
      amd64: x86_64
builds:
  - id: binary
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
    main: ./cmd/nginx-conf-generator/main.go
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: nginx-conf-generator
    tap:
      # The token determines the release type (Github/Gitlab).
      owner: bilalcaliskan
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    folder: Formula
    # Brew fails from multiple 32-bit arm versions.
    # Specify which version should be used.
    goarm: 6
    homepage: https://github.com/bilalcaliskan/nginx-conf-generator
    license: apache-2.0
    description: nginx-conf-generator gets the port of NodePort type services from a cluster and manages Nginx configuration
