---
name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This bot triages issues and PRs according to the following rules:
          - After 180d of inactivity, lifecycle/stale is applied.
          - After 90d of inactivity since lifecycle/stale was applied, lifecycle/rotten is applied and the issue is closed.
          You can:
          - Make a comment to remove the stale label and show your support. The 180d days reset.
          - If an issue has lifecycle/rotten and is closed, comment and ask maintainers if they'd be interseted in reopening"
          stale-pr-message: "This bot triages issues and PRs according to the following rules:
          - After 180d of inactivity, lifecycle/stale is applied.
          - After 90d of inactivity since lifecycle/stale was applied, lifecycle/rotten is applied and the PR is closed.
          You can:
          - Make a comment to remove the stale label and show your support. The 180d days reset.
          - If a PR has lifecycle/rotten and is closed, comment and ask maintainers if they'd be interseted in reopening."
          days-before-stale: 180
          days-before-close: 90
          stale-issue-label: 'lifecycle/stale'
          stale-pr-label: 'lifecycle/stale'
          exempt-issue-label: 'lifecycle/frozen'
          exempt-pr-label: 'lifecycle/frozen'
          close-issue-label: 'lifecycle/rotten'
          close-pr-label: 'lifecycle/rotten'
